---
title: "16S_Microbial_Community_Analysis"
author: "Dan Shelley"
date: "`r Sys.Date()`"

output:
  html_document:
    theme: flatly
    css: styles.css
    toc: true
    toc_float: true
    toc_depth: 3
    fig_width: 12
    fig_height: 6
---

## User Variables

```{r defining_user_variables}

## Input Files from Qiime2 Pipeline
metadata_path <- "metadata.csv"
otu_table_path <- "feature-table.tsv"
taxonomy_table_path <- "taxonomy.tsv"
tree_path <- "tree.nwk"

## Assign an Output Directory
output_path <- "./"

## Assign min number of ASVs to prune
min_ASVs = 5

## Comparison Variables
group = "Sample_Name"

## Beta Diversity Variables
dist = "bray"
method = "PCoA"
pvalue_cutoff = 0.05
micromet = "adonis"
pair = TRUE

## Taxonomic Variables
tax_level <- "Class" 
```

```{r generate_output_directories, include = FALSE}

# Creating Higher Level Directory
analysis_path = paste(output_path,"/16S_Analysis/",sep = "");analysis_path
dir.create(analysis_path)

# Higher Level OTU Path
otupath = paste(analysis_path,"/OTU/",sep = "");otupath
dir.create(otupath)

# Sub OTU Paths
otupath_otu = paste(analysis_path,"/OTU/otutab",sep = "");otupath_otu
otupath_tax = paste(analysis_path,"/OTU/taxtab",sep = "");otupath_tax
otupath_otunorm = paste(analysis_path,"/OTU/otutab_norm",sep = "");otupath_otunorm
otupath_taxnorm = paste(analysis_path,"/OTU/otutax_norm",sep = "");otupath_taxnorm

dir.create(otupath_otu)
dir.create(otupath_tax)
dir.create(otupath_otunorm)
dir.create(otupath_taxnorm)

# Alpha Diversity
alppath = paste(analysis_path,"/alpha_diversity/",sep = "")
dir.create(alppath)

# Beta Diversity
betapath = paste(analysis_path,"/beta_diversity/",sep = "")
dir.create(betapath)

# Taxonomy 
taxapath = paste(analysis_path,"/taxonomy/",sep = "")
dir.create(taxapath)
```

```{r library_preperation, include = FALSE}
## R Installs
#BiocManager::install('ANCOMBC')
#BiocManager::install('cowplot')
#BiocManager::install('decontam')
#BiocManager::install('dplyr')
#BiocManager::install('fs')
#BiocManager::install('ggClusterNet')
#BiocManager::install('ggnewscale')
#BiocManager::install('ggplot2')
#BiocManager::install('ggpubr')
#BiocManager::install('ggsignif')
#BiocManager::install('ggstar')
#BiocManager::install('ggtext')
#BiocManager::install('ggthemes')
#BiocManager::install('ggtreeExtra')
#BiocManager::install('ggvenn')
#BiocManager::install('gsl')
#BiocManager::install('grid')
#BiocManager::install('indicspecies')
#BiocManager::install('magrittr')
#BiocManager::install('picante')
#BiocManager::install('RColorBrewer')
#BiocManager::install('tidyverse')
#BiocManager::install('vegan')
#BiocManager::install('svglite')
#BiocManager::install('DESeq2')
#BiocManager::install('ggrepel')
#BiocManager::install('scales')

## Github Install
#remotes::install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
#remotes::install_github("taowenmicro/EasyStat")
#remotes::install_github("taowenmicro/ggClusterNet")

## Library Loading
library(ANCOMBC)
library(cowplot)
library(decontam)
library(dplyr)
library(EasyStat)
library(fs)
library(ggClusterNet)
library(ggnewscale)
library(ggplot2)
library(ggpubr)
library(ggsignif)
library(ggstar)
library(ggtext)
library(ggthemes)
library(ggtreeExtra)
library(ggvenn)
library(gsl)
library(grid)
library(indicspecies)
library(magrittr)
library(pairwiseAdonis)
library(picante)
library(RColorBrewer)
library(tidyverse)
library(vegan)
library(rstatix)
library(svglite)
library(phyloseq)
library(ggrepel)
library(DESeq2)
library(scales)
```

## Generating a Phyloseq Object

```{r generating_phyloseq_object, include = FALSE}

## Generate a Phyloseq Object
# Feature Table #########################################################################
FEATURE_TABLE_CLEAN <- read.table(otu_table_path,
                                  header = TRUE, 
                                  row.names = 1, 
                                  sep = "\t")

FEATURE_TABLE_CLEAN <- as.matrix(FEATURE_TABLE_CLEAN)
FEATURE_TABLE_CLEAN <- otu_table(FEATURE_TABLE_CLEAN, taxa_are_rows = TRUE)

# Taxonomy Table #########################################################################
TAXONOMY_TABLE <- read.table(taxonomy_table_path,
                             sep = "\t", 
                             header = TRUE, 
                             row.names = 1)

TAXONOMY_SPLIT <- strsplit(as.character(TAXONOMY_TABLE$Taxon), ";")

TAXONOMY_SPLIT_FORMATTED <- lapply(TAXONOMY_SPLIT, function(x) {
  length(x) <- 7 
  return(x)
})

TAXONOMY_MATRIX <- as.matrix(do.call(rbind, TAXONOMY_SPLIT_FORMATTED))

# Remove prefixes like "d__", "p__" etc.
TAXONOMY_MATRIX <- sub("^[a-z]__*", "", TAXONOMY_MATRIX)  # removes d__, p__, etc.
TAXONOMY_MATRIX[TAXONOMY_MATRIX == ""] <- NA # now we fill in the remaining empty gaps with NAs so R doesn't get confused

# Set column names (use "Domain" or "Kingdom" as you prefer)
colnames(TAXONOMY_MATRIX) <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")
# Add back the ASV IDs which were lost from our original data frame
rownames(TAXONOMY_MATRIX) <- rownames(TAXONOMY_TABLE)

# Convert to phyloseq tax_table object
TAXONOMY_TABLE <- phyloseq::tax_table(TAXONOMY_MATRIX)

# Metadata ###############################################################################
METADATA_TABLE <- read.csv(metadata_path, 
                            row.names = 1, 
                            na.strings="", 
                            stringsAsFactors = TRUE)


# Match Metadata Sample IDs to those in the feature table
METADATA_TABLE <- METADATA_TABLE[rownames(METADATA_TABLE) %in% colnames(FEATURE_TABLE_CLEAN), ]
METADATA_TABLE$Sample.name <- rownames(METADATA_TABLE)

METADATA_TABLE <- sample_data(METADATA_TABLE)

# Tree ###################################################################################

ROOTED_TREE <- read_tree(tree_path)

# Generate the PhyloSeq Object ###########################################################
PHYLOSEQ_OBJ <- phyloseq(FEATURE_TABLE_CLEAN, TAXONOMY_TABLE, METADATA_TABLE, ROOTED_TREE)

```
#### Alpha Rarefraction Curve

```{r generating_alpha_rarefraction}
# Calculating Rarefraction Curve

set.seed(2006576) # reproducibility

# Use original clean phyloseq object
dat <- PHYLOSEQ_OBJ

# Define depths
lib_sizes <- sample_sums(dat)
min_lib   <- min(lib_sizes)
max_lib   <- max(lib_sizes)

# Start with your candidate depths
depths <- seq(min_lib, max_lib, by = 100)
sample_var <- group 

# Initialize list
richness_list <- list()

for (d in depths) {
  set.seed(2006576)
  rare_dat <- rarefy_even_depth(dat, sample.size = d, rngseed = 2006576, verbose = FALSE, replace = FALSE)
  
  richness <- estimate_richness(rare_dat, measures = "Observed")
  richness$SampleID <- rownames(richness)
  richness$Depth <- d
  richness_list[[as.character(d)]] <- richness
}

# Combine results
rare_df <- bind_rows(richness_list)

# Add metadata
metadata <- data.frame(sample_data(dat))
metadata$SampleID <- rownames(metadata)
rare_df <- left_join(rare_df, metadata, by = "SampleID")

# Summarize mean & SE per group
summary_df <- rare_df %>%
  group_by(Depth, !!sym(sample_var)) %>%
  mutate(
    Richness_mean = mean(Observed, na.rm = TRUE),
    Richness_se   = sd(Observed, na.rm = TRUE) / sqrt(n())
  ) %>%
  ungroup()

```

```{r plotting_alpha_rarefraction}

## Plotting the Rarefraction Curve
ORG_PHYLO_RARE <- ggplot(summary_df, aes(x = Depth, y = Richness_mean, color = SampleID)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = Richness_mean - Richness_se,
                  ymax = Richness_mean + Richness_se,
                  fill = SampleID), alpha = 0.2, color = NA) +
  scale_color_discrete(labels = summary_df$SampleID) +
  scale_fill_discrete(labels = summary_df$SampleID) +
  scale_x_continuous(breaks = seq(0, 100000, by = 5000))+
  labs(title = "",
       x = "Sequencing Depth (n)",
       y = "Mean Observed ASVs (n)",
       color = "Species",
       fill = "Species") +
  theme_classic()+
  theme(axis.title.x=element_text(size=14), axis.title.y=element_text(size=14, face = "bold"))+
  theme(axis.text.x=element_text(size=13, angle = 35, hjust = 1, vjust = 1), axis.text.y=element_text(size=13))+
  theme(legend.title=element_text(size=14, face = "bold"), legend.text=element_text(size=13))+
  theme(legend.position="right")

FileName <- paste(alppath,"Refraction_Curve", ".svg", sep = "")
ggsave(FileName, ORG_PHYLO_RARE, width = 10, height = 10, limitsize = FALSE)
```

```{r}
ORG_PHYLO_RARE
```

## Removing Contamination

```{r decontam_remove_contaminants, include = FALSE}
# Remove incredibly low taxa
PHYLOSEQ_OBJ <- filter_taxa(PHYLOSEQ_OBJ, function(x) sum(x) >= min_ASVs, prune = TRUE)

# Add sequencing depth to sample metadata
sample_data(PHYLOSEQ_OBJ)$SequencingDepth <- sample_sums(PHYLOSEQ_OBJ)

# Identify contaminants with the "combined" method
contam_combined <- isContaminant(
  PHYLOSEQ_OBJ,
  method = "combined",
  conc = sample_data(PHYLOSEQ_OBJ)$SequencingDepth,
  neg  = sample_data(PHYLOSEQ_OBJ)$Control == "Y"  # logical vector
)

# How many contaminants?
sum(contam_combined$contaminant)

# Extract contaminant taxa as a character vector (NOT a list)
contaminants <- rownames(contam_combined)[contam_combined$contaminant]

# Double-check overlap with your phyloseq object
length(contaminants)
length(intersect(contaminants, taxa_names(PHYLOSEQ_OBJ)))

# Prune contaminants
PHYLOSEQ_OBJ_CLEAN <- prune_taxa(
  !(taxa_names(PHYLOSEQ_OBJ) %in% contaminants),
  PHYLOSEQ_OBJ
)
```

```{r decontam_output}
# Prior to decontamination
ntaxa(PHYLOSEQ_OBJ); 

# Following decontamination
ntaxa(PHYLOSEQ_OBJ_CLEAN)
```

## Basic Information Plots

```{r}
### Overide Original Object to remove controls. 
PHYLOSEQ_OBJ <- PHYLOSEQ_OBJ_CLEAN
PHYLOSEQ_OBJ <- subset_samples(PHYLOSEQ_OBJ_CLEAN, Control != "Y")
table(sample_data(PHYLOSEQ_OBJ)$Control)

# Basic Information

## Output OTU Table
otu = as.data.frame(t(ggClusterNet::vegan_otu(PHYLOSEQ_OBJ)))
FileName <- paste(otupath,"/otutab.csv", sep = "")
write.csv(otu,FileName,sep = ",")

## Output Taxa Table
tax = as.data.frame((ggClusterNet::vegan_tax(PHYLOSEQ_OBJ)))
FileName <- paste(otupath,"/tax.csv", sep = "")
write.csv(otu,FileName,sep = "")

## Output Relative Abundance Table
PHYLOSEQ_OBJ_rela  = phyloseq::transform_sample_counts(PHYLOSEQ_OBJ, function(x) x / sum(x) );PHYLOSEQ_OBJ_rela 
otu_norm = as.data.frame(t(ggClusterNet::vegan_otu(PHYLOSEQ_OBJ_rela)))
FileName <- paste(otupath,"/otutab_norm.csv", sep = "")
write.csv(otu_norm,FileName,sep = "")

## Output Relative Abundance Taxa Table
otutax <- cbind(as.data.frame(t(ggClusterNet::vegan_otu(PHYLOSEQ_OBJ_rela))),as.data.frame((ggClusterNet::vegan_tax(PHYLOSEQ_OBJ_rela))))
FileName <- paste(otupath,"/otutax_norm.csv", sep = "")
write.csv(otutax,FileName,sep = "")

## Generate Relative Abundance and Counts OTUs and Taxa for each taxonomic level
for (i in 2: length(phyloseq::rank_names(PHYLOSEQ_OBJ))) {
  psi  <- ggClusterNet::tax_glom_wt(ps = PHYLOSEQ_OBJ,ranks = phyloseq::rank_names(PHYLOSEQ_OBJ)[i])
  #--raw otu tab
  otu = as.data.frame(t(ggClusterNet::vegan_otu(psi)))
  FileName <- paste(otupath_otu,'/',phyloseq::rank_names(PHYLOSEQ_OBJ)[i],".csv", sep = "")
  write.csv(otu,FileName,sep = "")
  # tax table
  tax = as.data.frame((ggClusterNet::vegan_tax(PHYLOSEQ_OBJ)))
  FileName <- paste(otupath_tax,'/',phyloseq::rank_names(PHYLOSEQ_OBJ)[i],".csv", sep = "")
  write.csv(otu,FileName,sep = "")
  
  psi_rela  = phyloseq::transform_sample_counts(psi, function(x) x / sum(x) );psi_rela 
  #--norm otu tab
  otu_norm = as.data.frame(t(ggClusterNet::vegan_otu(psi_rela)))
  FileName <- paste(otupath_otunorm,'/',phyloseq::rank_names(psi)[i],".csv", sep = "")
  write.csv(otu_norm,FileName,sep = "")
  
  otutax <- cbind(as.data.frame(t(ggClusterNet::vegan_otu(psi_rela))),as.data.frame((ggClusterNet::vegan_tax(psi_rela))))
  FileName <- paste(otupath_taxnorm,'/',phyloseq::rank_names(PHYLOSEQ_OBJ)[i],".csv", sep = "")
  write.csv(otutax,FileName,sep = "")
}

```

## Alpha Diversity

```{r}
## Perform Diversity Measures

set.seed(2006576)

axis_order =  phyloseq::sample_data(PHYLOSEQ_OBJ)$type %>%unique();axis_order
  ps11 <-  PHYLOSEQ_OBJ
  mapping = phyloseq::sample_data(ps11)
  ps11 = phyloseq::filter_taxa(ps11, function(x) sum(x ) >0 , TRUE); ps11
  colnames(mapping) = gsub(group,"AA", colnames(mapping))
  mapping$Group = mapping$AA
  mapping$Group = as.factor(mapping$Group)
  
  # mapping$Group 
  count = as.data.frame(t(ggClusterNet::vegan_otu(ps11)))
  alpha=vegan::diversity(count, "shannon")
  x = t(count)
  
  Shannon = vegan::diversity(x)  
  Inv_Simpson <- vegan::diversity(x, index = "invsimpson")
  S <- vegan::specnumber(x);S 
  S2 = rowSums(x>0)

Pielou_evenness <- Shannon/log(S)
  Simpson_evenness <- Inv_Simpson/S
  est <- vegan::estimateR(x)
  est <- vegan::estimateR(x)
  Richness <- est[1, ]
  Chao1 <- est[2, ]
  ACE <- est[4, ]
  report = cbind(Shannon, Inv_Simpson, Pielou_evenness, Simpson_evenness,
                 Richness, Chao1,ACE) 
  head(report)

alp = merge(mapping,report , by="row.names",all=F)
index = c("Shannon","Inv_Simpson","Pielou_evenness","Simpson_evenness" ,"Richness" ,"Chao1","ACE" )
index = alp
sel = c(match("Shannon",colnames(index)),
        match("Inv_Simpson",colnames(index)),
        match("Pielou_evenness",colnames(index)),
        match("Simpson_evenness",colnames(index)),
        match("Richness",colnames(index)),
        match("Chao1",colnames(index)),
        match("ACE",colnames(index)))

data = cbind(data.frame(ID = 1:length(index$Group),group = index$Group),index[sel])
head(index)

result = EasyStat::MuiaovMcomper2(data = data,num = c(3:9))

FileName <- paste(alppath,"/alpha_diversity_different_label.csv", sep = "")
write.csv(result,FileName,sep = "")
FileName <- paste(alppath,"/alpha_diversity_index.csv", sep = "")
write.csv(index,FileName,sep = "")
```

```{r generating_alpha_plot, include = FALSE}
## Generate a Alpha Box Plot

result1 = EasyStat::FacetMuiPlotresultBox(data = data,num = c(3:9),
                                result = result,
                                sig_show ="abc",ncol = 3 )

p1_1 = result1[[2]] %>% ggplot(aes(x=group , y=dd )) + 
  geom_boxplot(alpha=1, aes(fill=group)) +
  geom_point(aes(color = group), size=3, alpha=0.5)+
  labs(x="", y="")+
  facet_wrap(.~name,scales="free_y",ncol  = 3) +
  ggplot2::scale_x_discrete(limits = axis_order) + 
  guides(color=guide_legend(title = NULL),
         shape=guide_legend(title = NULL),
         fill = guide_legend(title = NULL)
         ) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

FileName <- paste(alppath,"Alpha_box", ".svg", sep = "")
ggsave(FileName, p1_1, width = 15, height = 15, limitsize = FALSE)
```

#### Alpha Diversity Measures

```{r plotting_diversity_to_RMD, fig.width=10, fig.height=10}
p1_1
```

#### Statistical Analysis
```{r ANOVA_on_Alpha}
## Perform and Extract Comparison Information

# ANOVA for each metric 

anova_Shannon <- anova_test(data = index, Shannon ~ AA) %>%
  get_anova_table() %>%
  as_tibble() %>%                # Convert to tibble
  mutate(metric = "Shannon")

anova_InvSimpson <- anova_test(data = index, Inv_Simpson ~ AA) %>%
  get_anova_table() %>%
  as_tibble() %>%
  mutate(metric = "Inv_Simpson")

anova_Pielou <- anova_test(data = index, Pielou_evenness ~ AA) %>%
  get_anova_table() %>%
  as_tibble() %>%
  mutate(metric = "Pielou_evenness")

anova_Evenness <- anova_test(data = index, Simpson_evenness ~ AA) %>%
  get_anova_table() %>%
  as_tibble() %>%
  mutate(metric = "Simpson_evenness")

anova_Richness <- anova_test(data = index, Richness ~ AA) %>%
  get_anova_table() %>%
  as_tibble() %>%
  mutate(metric = "Richness")

anova_Chao1 <- anova_test(data = index, Chao1 ~ AA) %>%
  get_anova_table() %>%
  as_tibble() %>%
  mutate(metric = "Chao1")

anova_ACE <- anova_test(data = index, ACE ~ AA) %>%
  get_anova_table() %>%
  as_tibble() %>%
  mutate(metric = "ACE")

# Combine ANOVA results
anova_all <- bind_rows(anova_Shannon, anova_InvSimpson, anova_Pielou, anova_Evenness,
                       anova_Richness, anova_Chao1, anova_ACE)

posthoc_all <- bind_rows(
  tukey_hsd(index, Shannon ~ AA) %>% mutate(metric = "Shannon"),
  tukey_hsd(index, Inv_Simpson ~ AA) %>% mutate(metric = "Inv_Simpson"),
  tukey_hsd(index, Pielou_evenness ~ AA) %>% mutate(metric = "Pielou_evenness"),
  tukey_hsd(index, Simpson_evenness ~ AA) %>% mutate(metric = "Simpson_evenness"),
  tukey_hsd(index, Richness ~ AA) %>% mutate(metric = "Richness"),
  tukey_hsd(index, Chao1 ~ AA) %>% mutate(metric = "Chao1"),
  tukey_hsd(index, ACE ~ AA) %>% mutate(metric = "ACE")
)


FileName <- paste(alppath,"/alpha_diversity_anova_table.csv", sep = "")
write.csv(anova_all,FileName,sep = "")
FileName <- paste(alppath,"/alpha_diversity_tukey_post_hoc.csv", sep = "")
write.csv(posthoc_all,FileName,sep = "")
```

#### ANOVA Table
```{r}
anova_all
```

#### Post-Hoc Test
```{r}
posthoc_all
```

## Beta Diversity

```{r generating_beta_diversity_measure}
## Beta Diversity Analysis
# Generate Abundance Table

ps1_rela = phyloseq::transform_sample_counts(PHYLOSEQ_OBJ, function(x) x / sum(x) )
sample_data(ps1_rela)$SequencingDepth <- sample_sums(PHYLOSEQ_OBJ)

if (method == "DCA") {
  ordi = phyloseq::ordinate(ps1_rela, method=method, distance=dist)
  points = ordi$rproj[,1:2]
  colnames(points) = c("x", "y")
  eig = ordi$evals^2
}

if (method == "CCA") {
  ordi = phyloseq::ordinate(ps1_rela, method=method, distance=dist)
  points = ordi$CA$v[,1:2]
  colnames(points) = c("x", "y") 
  eig = ordi$CA$eig^2
}

if (method == "RDA") {
  ordi = phyloseq::ordinate(ps1_rela, method=method, distance=dist)
  points = ordi$CA$v[,1:2]
  colnames(points) = c("x", "y") 
  eig = ordi$CA$eig
}

if (method == "MDS") {
  ordi = phyloseq::ordinate(ps1_rela, method=method, distance=dist)
  points = ordi$vectors[,1:2]
  colnames(points) = c("x", "y")
  eig = ordi$values[,1]
}

if (method == "PCoA") {
  unif = phyloseq::distance(ps1_rela , method=dist, type="samples")
  pcoa = stats::cmdscale(unif, k=2, eig=T) 
  points = as.data.frame(pcoa$points) 
  colnames(points) = c("x", "y")
  eig = pcoa$eig
}

otu_table = as.data.frame(t(ggClusterNet::vegan_otu(ps1_rela )))
if (method == "PCA") {
  otu.pca = stats::prcomp(t(otu_table), scale.default = TRUE)
  points = otu.pca$x[,1:2]
  colnames(points) = c("x", "y") 
  eig=otu.pca$sdev
  eig=eig*eig
}

if (method == "LDA") {
  data = t(otu_table)
  data = as.data.frame(data)
  data = scale(data, center = TRUE, scale = TRUE)
  dim(data)
  data1 = data[,1:10]
  map = as.data.frame(sample_data(ps1_rela))
  model = MASS::lda(data, map$Group)

  ord_in = model
  axes = c(1:2)
  points = data.frame(predict(ord_in)$x[, axes])
  colnames(points) = c("x", "y")
  eig= ord_in$svd^2
}

if (method == "NMDS") {
  ordi = phyloseq::ordinate(ps1_rela, method=method, distance=dist)
  points = ordi$points[,1:2]
  colnames(points) = c("x", "y") 
  stress = ordi$stress
  stress= paste("stress",":",round(stress,2),sep = "")
}

if (method == "t-sne") {
  data = t(otu_table)
  data = as.data.frame(data)
  data = scale(data, center = TRUE, scale = TRUE)

  dim(data)
  map = as.data.frame(sample_data(ps1_rela))

  tsne = Rtsne::Rtsne(data,perplexity = 3)

  points = as.data.frame(tsne$Y)
  row.names(points) =  row.names(map)
  colnames(points) = c("x", "y")
  stress= NULL
}

## adonis
otu_adonis_df <- as.data.frame(t(otu_table(ps1_rela)))
adonis_dist <- vegdist((otu_adonis_df), method = dist)
meta_df <- as.data.frame(sample_data(ps1_rela))
meta_df <- data.frame(meta_df, row.names = rownames(meta_df))
meta_df$type <- as.factor(meta_df$Sample_Name)

adonis_result <- adonis2(adonis_dist ~ type, data = meta_df, by = "margin", permutations = 999)

FileName <- paste(betapath,"/single_PERMANOVA.csv", sep = "")
write.csv(adonis_result,FileName,sep = ",")

## Plotting the distance plot

map = as.data.frame(phyloseq::sample_data(ps1_rela))
map$Group = as.factor(map$Sample_Name)
colbar = length(levels(map$type))

points = cbind(points, map[match(rownames(points), rownames(map)), ])
# head(points)
points$ID = row.names(points)

if (method %in% c("DCA", "CCA", "RDA",  "MDS", "PCoA","PCA","LDA","NMDS")) {
  p2 =ggplot(points, aes(x=x, y=y, fill = Group)) +
    geom_point(alpha=.7, size=5, pch = 21) +
    labs(x=paste0(method," 1 (",format(100*eig[1]/sum(eig),digits=4),"%)"),
         y=paste0(method," 2 (",format(100*eig[2]/sum(eig),digits=4),"%)"),
        fill = "Group") +
    stat_ellipse(linetype=2,level=0.95,aes(group=Group, colour=Group)) +
    theme_bw() +
    theme(legend.position = 'bottom')  +
    scale_x_continuous(
    labels = number_format(accuracy = 0.01)
  ) +
  scale_y_continuous(
    labels = number_format(accuracy = 0.01)
  )

  p3 <- ggplot(points, aes(x = x, y = y, fill = SequencingDepth)) +
  geom_point(alpha = .7, size = 5, pch = 21) +
  scale_fill_viridis_c() +
  labs(
    x = paste0(method, " 1 (", format(100 * eig[1] / sum(eig), digits = 4), "%)"),
    y = paste0(method, " 2 (", format(100 * eig[2] / sum(eig), digits = 4), "%)"),
    fill = "Sequencing Depth") +
  theme_bw() +
  theme(legend.position = 'bottom')  +
  scale_x_continuous(
    labels = number_format(accuracy = 0.01)
  ) +
  scale_y_continuous(
    labels = number_format(accuracy = 0.01)
  )
}

p4 <- ggarrange(p2, p3, 
               ncol = 2,
               nrow = 1)


FileName <- paste(betapath,"/", method, "_Type.svg", sep = "")
ggsave(FileName, p2, width = 10, height = 10, limitsize = FALSE)
FileName <- paste(betapath,"/", method, "_Seq_Depth.svg", sep = "")
ggsave(FileName, p3, width = 10, height = 10, limitsize = FALSE)
FileName <- paste(betapath,"/", method, "_Arranged.svg", sep = "")
ggsave(FileName, p4, width = 20, height = 10, limitsize = FALSE)
```

```{r}
p4
```

## Taxonomic Analysis

```{r}
#TAXA DOT PLOT - PHYLA

# Collapse to chosen level
PHYLOSEQ_OBJ_TAXA <- tax_glom(PHYLOSEQ_OBJ, taxrank = tax_level)

# Relative abundance
PHYLOSEQ_OBJ_RELATIVE_ABUND <- transform_sample_counts(PHYLOSEQ_OBJ_TAXA, function(x) x / sum(x))

# Melt
PHYLOSEQ_OBJ_PLOT <- psmelt(PHYLOSEQ_OBJ_RELATIVE_ABUND)

# ---- NEW PART: Identify top 20 taxa ----

top_taxa <- PHYLOSEQ_OBJ_PLOT %>%
  as_tibble() %>%  # ensure a tibble, not an S4/IRanges object
  group_by(.data[[tax_level]]) %>%
  summarise(mean_abundance = mean(Abundance, na.rm = TRUE), .groups = "drop") %>%
  arrange(desc(mean_abundance)) %>%
  dplyr::slice(1:30) %>%
  dplyr::pull(.data[[tax_level]]) %>%
  unique()


# ---- Recode everything else as "Other" ----
PHYLOSEQ_OBJ_PLOT <- PHYLOSEQ_OBJ_PLOT %>%
  mutate(!!sym(tax_level) := if_else(!!sym(tax_level) %in% top_taxa,
                                     !!sym(tax_level),
                                     "Other"))


PHYLOSEQ_OBJ_PLOT <- PHYLOSEQ_OBJ_PLOT %>%
  group_by(Sample, Sample_Name, !!sym(tax_level)) %>% 
  summarise(Abundance = sum(Abundance), .groups = "drop")


taxa_order <- c(top_taxa, "Other")
PHYLOSEQ_OBJ_PLOT[[tax_level]] <- factor(PHYLOSEQ_OBJ_PLOT[[tax_level]], levels = taxa_order)

# Filter out abundances below 0.1
PHYLOSEQ_OBJ_PLOT <- PHYLOSEQ_OBJ_PLOT %>%
  filter(Abundance >= 0.01) # Do not show the rare samples

PHYLOSEQ_OBJ_PLOT$label <- paste0(PHYLOSEQ_OBJ_PLOT$Sample.name, "_", PHYLOSEQ_OBJ_PLOT$type_detail)

## Wrap the Facet Labels
facet_labels_wrapped <- setNames(
  stringr::str_wrap(levels(PHYLOSEQ_OBJ_PLOT$type), width = 10),
  levels(PHYLOSEQ_OBJ_PLOT$type)
)

p4 <- ggplot(PHYLOSEQ_OBJ_PLOT, 
       aes(x = Sample, 
           y = !!sym(tax_level), 
           size = Abundance, 
           color = !!sym(tax_level))) +
  geom_point(alpha = 0.7) +
  theme_bw() +
  facet_wrap(~ Sample_Name, scales = 'free_x', nrow = 1) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  ylab(tax_level) +
  xlab("") +
  scale_size_continuous(range = c(1, 20)) + 
  guides(color = guide_legend(nrow = 20, byrow = FALSE, override.aes = list(size = 6))) +
  theme(strip.text = element_text(size = 12, face = "bold")) +
  theme(axis.title.x=element_text(size=12), axis.title.y=element_text(size=12)) +
  theme(axis.text.x=element_text(size=12), axis.text.y=element_text(size=12)) +
  theme(legend.title=element_text(size=12, face = "bold"), legend.text=element_text(size=12)) +
  theme(legend.position="right")


FileName <- paste(alppath,"Dot_Taxonomy.svg", sep = "")
ggsave(FileName, p4, width = 30, height = 10, limitsize = FALSE)
```

```{r plotting_taxonomy, fig.width=20, fig.height=20}
p4
```

